baseURL = "https://michelaquino.github.io/"
languageCode = "pt-br"
title = "Michel Aquino"
author = "Michel Aquino"
canonifyurls = true
paginate = 3

googleAnalytics = ""
disqusShortname = "spf13"

theme = "hyde"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/michelaquino"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/michel-aquino-415a4424/"},
      {Name = "Quem sou eu", URL = "/about"}
  ]

[params]
  description = "Software Development"