## Basic Configuration
baseURL = "https://michelaquino.github.io/"
languageCode = "en"

title = "Michel Aquino"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

# summarylength = 30

paginate = 5

## Site Settings
[params]
    author = "Michel Aquino"
    title = "Michel Aquino"
    description = "Michel Aquino"
    #authorimage = "/img/logo-gray.png"
    dateformat = "Jan 2, 2006"

    # sidebar, copyright & license
    logoimage = "/img/logo-gray.png"
    copyright = "michelaquino"
    since = 2021
    #license = "CC BY-SA 4.0"
    #licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    #showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    linkedin = "michel-aquino-415a4424"
    github = "michelaquino"
    gitlab = "michelaquino"
    #twitter = "<username>"
    #stackoverflow = "<username>"
    keybase = "michelaquino"
    email = "michelaquino @ mailbox.org"
    rss = ""

## Main Menu
[[menu.main]]
    name = "Home"
    weight = 100
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/post/"
[[menu.main]]
    name = "Tags"
    weight = 100
    identifier = "tags"
    url = "/tags/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"